language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - tip

services:
 - mysql
 - postgres
 - sqlite3
 - mongodb

before_script:
 - go get github.com/lib/pq
 - go get github.com/mattn/go-sqlite3
 - go get github.com/ziutek/mymysql/godrv
 - go get github.com/go-sql-driver/mysql
 - go get labix.org/v2/mgo
 - mysql -e "CREATE DATABASE pouch;"
 - mysql -u root -e "GRANT ALL ON pouch.* TO pouch@localhost IDENTIFIED BY 'pouch'"
 - psql -c "CREATE DATABASE pouch;" -U postgres
 - psql -c "CREATE USER "pouch" WITH SUPERUSER PASSWORD 'pouch';" -U postgres
